controllers/UserRegionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\UserReferensi;
use app\models\UserRegionSearch;
use app\models\Area;
use app\models\Region;
use app\models\Priviledge;
use app\models\LogUser;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Excel;
use \yii\web\Response;
use yii\helpers\Json;

/**
 * UserReferensiController implements the CRUD actions for UserReferensi model.
 */
class UserRegionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    // [
                    //     'allow' => true,
                    //     'actions'=>['my-white-list'],
                    //     'roles' => ['@'],
                    //     'matchCallback' => function($rules,$action){
                    //         return $this->isAcceptedRegion($rules,$action);
                    //         // return status= =12;
                    //     }
                    // ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function($rules,$action){
                            return $this->isAcceptedRegion($rules,$action);
                        }
                    ],
                    [
                        'allow' => false
                    ]
                ]
            ]
        ];
    }

    // private function isAccepted($rules,$action){
    //     //jika dia admin cek table priviledge
    //     $status = Yii::$app->user->identity->status;
    //     if(in_array($status, [5])){
    //         $cek = Priviledge::find()->where(['nama' => 'User White List','status'=>1])->one();
    //         if(!empty($cek)){
    //             return true;
    //         }else{
    //             return false;
    //         }
    //     }
    //     //jika approver return true
    //     if(in_array($status, [10])){
    //         return true;
    //     }else{
    //     //jika selain itu return false
    //         return false;
    //     }
        
    // }

    private function isAcceptedRegion($rules,$action){
        //jika dia admin cek table priviledge
        $status = Yii::$app->user->identity->status;
        return $status ==12;
    }

    /**
     * Lists all UserReferensi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserRegionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        //  $dataProvider = new ActiveDataProvider([
        //     'query' => UserReferensi::find()->orderBy(['nip' => SORT_ASC])->where(['region_id' => Yii::$app->user->identity->region_id]),
        //     // 'query' => Notifikasi::find()->orderBy(['created_at' => SORT_DESC]),
        // ]);
        $excelModel = Excel::find()->where(['class'=>'userRegion'])->one();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'excelModel' => $excelModel
        ]);
    }

    /**
     * Displays a single UserReferensi model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->redirect(['index']);
        
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UserReferensi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserReferensi();
        $model->region_id = Yii::$app->user->identity->region->id;
        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            LogUser::logHitUser(LogUser::CREATE_USERREGION,LogUser::SUCCESS,Yii::$app->user->identity->nip,Yii::$app->user->identity->id);
            \Yii::$app->getSession()->setFlash('success', 'Your data has been craeted');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing UserReferensi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            LogUser::logHitUser(LogUser::UPDATE_USERREGION,LogUser::SUCCESS,Yii::$app->user->identity->nip,Yii::$app->user->identity->id);
            \Yii::$app->getSession()->setFlash('success', 'Your data has been updated');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing UserReferensi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->deleteWithRelated();
        LogUser::logHitUser(LogUser::DELETE_USERREGION,LogUser::SUCCESS,Yii::$app->user->identity->nip,Yii::$app->user->identity->id);
        \Yii::$app->getSession()->setFlash('success', 'Your data has been updated');

        return $this->redirect(['index']);
    }

    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            // return $this->redirect(['index']);
            return ['forceClose'=>true,'forceReload'=>'#kv-pjax-container-user-referensi'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    
    /**
     * Finds the UserReferensi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return UserReferensi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserReferensi::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDeleteAll()
    {
        $connection = Yii::$app->db;
        $transaction = $connection->beginTransaction();
        $model = null;
        try{
            UserReferensi::deleteAll(['region_id'=> Yii::$app->user->identity->region_id]);
            \Yii::$app->getSession()->setFlash('success', 'Your data has been updated');
            $transaction->commit();
        } catch (\Exception $e) {
            if(!empty($model)){

                \Yii::$app->getSession()->setFlash('error', $model->name." gagal dihapus");   
            }else{
                
                \Yii::$app->getSession()->setFlash('error', "error");   
            }
            $transaction->rollBack();
            // throw $e;
        } catch (\Throwable $e) {
            \Yii::$app->getSession()->setFlash('error', $e->getMessage());   
            $transaction->rollBack();
            // throw $e;
        }
        return $this->redirect(['index']);
    }
    public function actionImport(){
        $request = Yii::$app->request;
        if($request->isGet){
            return $this->redirect(['index']);

        }else{
            $modelExcel = Excel::findOne($request->post('Excel')['id']);
            $modelExcel->load($request->post());
            if(!$modelExcel->upload()){
                \Yii::$app->getSession()->setFlash('error', 'Upload failed');   
                return $this->redirect(['index']);
            }

            $data = $modelExcel->importExcel();
            if(empty($data)){
                \Yii::$app->getSession()->setFlash('error', 'wrong format');   
                
            }
            // var_dump($data);
            // die();
            $connection = Yii::$app->db;
            $transaction = $connection->beginTransaction();

             try{
                UserReferensi::deleteAll(['region_id'=> Yii::$app->user->identity->region_id]);

                $this->importData($data);
                $total = count($data);
                $pesan = "Import User Region berhasil dilakukan sebanyak ".$total." data";
                LogUser::logHitUser(LogUser::IMPORT_USERREGION,LogUser::SUCCESS,Yii::$app->user->identity->nip,Yii::$app->user->identity->id,$pesan);
                \Yii::$app->getSession()->setFlash('success', 'Your data has been updated');   
                $transaction->commit();
            } catch (\Exception $e) {
                // \Yii::$app->getSession()->setFlash('error', $e->getMessage());   
                \Yii::$app->getSession()->setFlash('error', 'Error');   
                $transaction->rollBack();
                // throw $e;
            } catch (\Throwable $e) {

views/user-region/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\depdrop\DepDrop;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\UserReferensi */
/* @var $form yii\widgets\ActiveForm */
if(empty($model->dob)){
    $model->dob = '1980-01-01';
}
?>

<div class="user-referensi-form">

    <?php $form = ActiveForm::begin(['options'=>['class'=>'']]); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'nip')->textInput(['maxlength' => true, 'placeholder' => 'Nip']) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'placeholder' => 'Nama']) ?>

    <?= $form->field($model, 'contact')->textInput(['maxlength' => true, 'placeholder' => 'Contact']) ?>

    <?php $areaList=ArrayHelper::map(app\models\Area::find()->where(['region_id' => Yii::$app->user->identity->region_id])->all(), 'id', 'name' ); ?> 
    <?= //Dependent Dropdown
        $form->field($model, 'area_id')->dropDownList($areaList);
    ?>

     <?= $form->field($model, 'dob')->widget(\kartik\datecontrol\DateControl::classname(), [
      'type' => \kartik\datecontrol\DateControl::FORMAT_DATE,
      'saveFormat' => 'php:Y-m-d',
      'ajaxConversion' => true,
      'options' => [
              'placeholder' => 'Start Date',
          'pluginOptions' => [
              'autoclose' => true
          ]
      ],
    ]); ?>
    
    <?= $form->field($model, 'lock', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user-region/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

views/user-region/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserReferensiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-user-referensi-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

<div class="col-md-9">
    <?= $form->field($model, 'nip')->textInput(['maxlength' => true, 'placeholder' => 'Nip'])->label(false) ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>
    <?= $form->field($model, 'lock', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>
</div>
<div class="col-md-3">
    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </div>
</div>
    <?php ActiveForm::end(); ?>

</div>

views/user-region/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UserReferensi */

$this->title = 'Create User Region';
$this->params['breadcrumbs'][] = ['label' => 'User Referensi', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-referensi-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user-region/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserReferensiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use yii\helpers\Html;
use kartik\export\ExportMenu;
use kartik\grid\GridView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\alert\AlertBlock;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;
use yii\bootstrap\Modal;


CrudAsset::register($this);


$this->title = 'User Region White List';
$this->params['breadcrumbs'][] = $this->title;
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
$this->registerJs($search);
?>

<?php $form = ActiveForm::begin(['action'=>Url::to(['user-region/import'],true),'options' => ['enctype' => 'multipart/form-data']]); ?>
<?= $form->field($excelModel, 'id')->hiddenInput()->label(false) ?>
<?= $form->field($excelModel, 'file')->fileInput(['accept' => 'application/vnd.ms-excel', 'required'=>true]) ?>
<?= Html::submitButton('Import' , 
    [
        'class' =>'btn btn-primary',
        'data-confirm' => Yii::t('yii', 'Are you sure you want to import?'),
    ]) 
?>

<?=Html::a('Export',Url::to(['user-region/export'],true),
    [
        'class'=>'btn btn-default',
        'data-confirm' => Yii::t('yii', 'Are you sure you want to export?'),
    ])
?>
<?= 

 AlertBlock::widget([
    'type' => AlertBlock::TYPE_ALERT,
    'useSessionFlash' => true
]);
?>
<?php ActiveForm::end(); ?>
<br/>
<div class="user-region-index">
    <div class="row">
        <div class="col-md-6">
                <?= Html::a('Create User White List', ['create'], ['class' => 'btn btn-success']) ?>
        </div>
        <div class="col-md-6">
            <?php //echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    </div>
<br/>

    <!-- <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Advance Search', '#', ['class' => 'btn btn-info search-button']) ?>
    </p>
    <div class="search-form" style="display:none">
        <?=  $this->render('_search', ['model' => $searchModel]); ?>
    </div> -->
    <?php 
    $gridColumn = [
        [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
        ],
        ['class' => 'yii\grid\SerialColumn'],
        ['attribute' => 'id', 'visible' => false],
        ['attribute'=>'nip','label'=>'Nip/sales code'],
        ['attribute'=>'name','label'=>'Nama'],
        // ['attribute'=>'dob'],
        [
            'attribute' => 'dob',
            'format' => ['date', 'php:d-m-Y'],
            'filterType'=> \kartik\grid\GridView::FILTER_DATE, 
            'filterWidgetOptions' => [
                    'options' => ['placeholder' => 'Select date'],
                    'pluginOptions' => [
                        'format' => 'dd-mm-yyyy',
                        'todayHighlight' => true
                    ]
            ],
        ],
        'contact',
        [
            'attribute' => 'area_id',
            'label' => 'Area',
            'value' => function($model){
                if(!empty($model->area)){
                    return $model->area->name;
                }else{
                    return "";
                }
            },
        ],
        [
            'attribute' => 'region_id',
            'label' => 'Region',
            'value' => function($model){
                if(!empty($model->region)){
                    return $model->region->name;
                }else{
                    return "";
                }
            },
        ],
        ['attribute' => 'lock', 'visible' => false],
        [
            'class' => 'kartik\grid\ActionColumn',
            'noWrap' => true,
            'template' => '{update}{delete}',
            'headerOptions'=>[
                'style'=>'color:#3c8dbc'
            ],
        ],
    ]; 
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumn,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-user-referensi']],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
            'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
                                ["bulk-delete"] ,
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Are you sure?',
                                    'data-confirm-message'=>'Are you sure want to delete this item'
                                ]),
                        ]).'&nbsp;'.
                         Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All ('.number_format($dataProvider->getTotalCount()).')',
                                ['delete-all'],
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    // 'role'=>'modal-remote-bulk',
                                    // 'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'name'=>'aksi',
                                    'value'=>'delete all',
                                    'type'=>'submit',
                                    // 'data-toggle'=>"modal",
                                    // 'data-target'=>'#ajaxCrudModal'
                                    // 'data-request-method'=>'post',
                                    // 'data-confirm-title'=>'Are you sure?',
                                    'data-confirm'=>'Are you sure want to Delete all these item'
                                ]
                        ).                                 
                        '<div class="clearfix"></div>',
        ],
        'export' => false,
        // your toolbar can include the additional full export menu
        'toolbar' => '',
        // 'toolbar' => [
        //     '{export}',
        //     ExportMenu::widget([
        //         'dataProvider' => $dataProvider,
        //         'columns' => $gridColumn,
        //         'target' => ExportMenu::TARGET_BLANK,
        //         'fontAwesome' => true,
        //         'dropdownOptions' => [
        //             'label' => 'Full',
        //             'class' => 'btn btn-default',
        //             'itemsBefore' => [
        //                 '<li class="dropdown-header">Export All Data</li>',
        //             ],
        //         ],
        //         'exportConfig' => [
        //             ExportMenu::FORMAT_PDF => false
        //         ]
        //     ]) ,
        // ],
    ]); ?>

</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/user-region/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UserReferensi */

$this->title = 'Update User Region: ' . ' ' . $model->nip;
$this->params['breadcrumbs'][] = ['label' => 'User Referensi', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-referensi-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user-region/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\UserReferensi */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User Region', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-Region-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= 'User Region'.' '. Html::encode($this->title) ?></h2>
        </div>
        <div class="col-sm-3" style="margin-top: 15px">
            
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ])
            ?>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'nip',
        'contact',
        ['attribute' => 'lock', 'visible' => false],
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>